# Generated by Django 5.2.4 on 2025-08-18 01:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resena_nombre_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPrecioUnificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.CharField(db_index=True, max_length=50)),
                ('producto_nombre', models.CharField(max_length=500)),
                ('producto_marca', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('precio_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_notificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Precio Unificada',
                'verbose_name_plural': 'Alertas de Precios Unificadas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ResenaUnificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.CharField(db_index=True, max_length=50)),
                ('producto_nombre', models.CharField(max_length=500)),
                ('producto_marca', models.CharField(blank=True, max_length=200, null=True)),
                ('producto_categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('valoracion', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('nombre_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_unificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña Unificada',
                'verbose_name_plural': 'Reseñas Unificadas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['producto_id', '-fecha_creacion'], name='core_resena_product_52db2b_idx'), models.Index(fields=['valoracion'], name='core_resena_valorac_0fbee2_idx')],
                'unique_together': {('producto_id', 'usuario')},
            },
        ),
    ]
