# Generated by Django 5.2.4 on 2025-08-28 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_mailing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Verificación de Email',
                'verbose_name_plural': 'Verificaciones de Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('immediate', 'Inmediato'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('disabled', 'Deshabilitado')], default='immediate', max_length=20)),
                ('unsubscribe_token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Email',
                'verbose_name_plural': 'Preferencias de Email',
            },
        ),
        migrations.CreateModel(
            name='EmailBounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bounce_type', models.CharField(choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce'), ('spam', 'Spam Report'), ('unsubscribe', 'Unsubscribe')], max_length=20)),
                ('bounce_reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Bounce',
                'verbose_name_plural': 'Email Bounces',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
