# Generated by Django 5.2.4 on 2025-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_email_models'),
    ]

    operations = [
        # Renombrar user_email a email en MailLog
        migrations.RenameField(
            model_name='maillog',
            old_name='user_email',
            new_name='email',
        ),
        
        # Cambiar el tipo de campo email en MailLog
        migrations.AlterField(
            model_name='maillog',
            name='email',
            field=models.CharField(max_length=500),
        ),
        
        # Cambiar el tipo de campo email en EmailVerification
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.CharField(max_length=500),
        ),
        
        # Cambiar el tipo de campo email en EmailPreference
        migrations.AlterField(
            model_name='emailpreference',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
        
        # Cambiar el tipo de campo email en EmailBounce
        migrations.AlterField(
            model_name='emailbounce',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
