# Generated by Django 5.2.4 on 2025-08-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_mailing_models'),
    ]

    operations = [
        # This migration fixes the database state by ensuring
        # that any remaining references to old models are cleaned up
        migrations.RunSQL(
            # Forward SQL - clean up any remaining problematic data
            """
            -- Delete any remaining AlertaUsuario records if they exist
            DELETE FROM core_alertausuario WHERE 1=1;
            
            -- Delete any remaining Alerta records if they exist  
            DELETE FROM core_alerta WHERE 1=1;
            
            -- Delete any remaining ProductoTienda records if they exist
            DELETE FROM core_productotienda WHERE 1=1;
            """,
            # Reverse SQL - no reverse operation needed
            """
            -- No reverse operation
            """
        ),
    ]
