# Generated by Django 5.2.4 on 2025-08-30 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_email_encryption_models'),
        ('core', '0007_auto_20250830_1738'),
    ]

    operations = [
    ]
