version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    environment:
      - DEBUG=False
    env_file:
      - .env
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery-worker:
    build: .
    command: celery -A etl.celery_app:app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A etl.celery_app:app beat --loglevel=info
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
